name: Dockerized Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering
    inputs:
      test_id:
        description: "Specify the Test ID to run manually"
        required: false
        default: "all"

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.test_id == 'all'
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t pytest-runner .

      # Run All Tests
      - name: Run All Tests
        run: |
          docker run -v $(pwd)/reports:/app/reports pytest-runner
      
      # Download reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports/
          retention-days: 7

  run-specific-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.test_id != 'all'
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t pytest-runner .

      # Run Specific Test
      - name: Run Test by ID
        env:
          TEST_ID: ${{ github.event.inputs.test_id }}
        run: |
          docker run -v $(pwd)/reports:/app/reports -e $TEST_ID pytest-runner
      
      # Download reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports/
          retention-days: 7